// const student ={
//     namee:"ganesh",
//     age:56,
//     marks:94,
// }


// const item={
//     price:100,
//     discount:50,
//     color:["red","mahesh"]
// }

// const post={
//     usernam:"@ganeshshindee",
//     contenet:"This is my first post",
//     likes:150,
//     repost:5,
//     tags:["@madhavshinde","@keshavShinde"]
// }

// const student2={
//     name:mahesh,
//     age:45,
// }


// const student3={
//     ganesh:{
//         grade:"a+",
//         marks:25
//     },
//     mahesh:{
//         grade:"a",
//         marks:56
//     },
//     mahsh :{
//         grade:"a",
//         marks:56
//     }
// }

// const classinfo=[{
//     name:"ganesh",
//     age:25,
//     city:"delhi"

// },
// {
//     name:"gan",
//     age:25,
//     city:"delhi"

// },
// {
//     name:"gah",
//     age:25,
//     city:"delhi"

// }]

let max=prompt("Enter the maximum number : ");
let random=Math.floor(Math.random()*max+1);
let guess=prompt("Enter your guess number generated by random function")
let count=10;
while(true){
    if(guess==random){
        alert("you guessed successfully!");
        break;
    }
    else if(guess<random){
        guess=prompt("your value is smaller than random and try again "+" you have "+ count +" Attemps left.");
        count--;
    }
    else if(guess>random){
        guess=prompt("your guessed value is larger than random")
        count--;
    }
    else if(guess=='quit'){
        alert("You quited!");
        break;
    }
    if(count<=0){
        alert("you have guessing limit excced")
        break;
    }
}
